action_alias launch_tab launch --type=tab --cwd=current

#foreground #121214
background #1D1F21
#cursor #a9b1d6

color0 #1a1b26
color8 #4e5173

color1 #F93E66
color9 #F93E66

color2 #6A8860
color10 #6A8860

color3 #E0AF68
color11 #E0AF68

color4 #7AA2F7
color12 #7AA2F7

color5 #C6AAD3
color13 #C6AAD3

color6 #4abaaf
color14 #4abaaf

color7 #acb0d0
color15 #acb0d0
sync_to_monitor yes
tab_bar_style powerline
tab_fade 0.25 0.5 0.75 1
active_tab_foreground   #000
active_tab_background   #eee
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #999
inactive_tab_font_style normal
font_family FiraCode-Regular
